### PR TITLE
First congress

### PR DESCRIPTION
**Pull request by countvajhula**
Gather the results of the [first congress](https://github.com/drym-org/foundation/wiki/First-Congress), tally everything up and produce the results.

**Remaining items**:
- [x] Agree on price and valuation (see comments below)
- [x] Maintain a [companion WIP PR](https://github.com/drym-org/symex.el/pull/66) against the Symex repo containing the DIA results.
- [x] Review this PR including sign-off on the companion PR.
- [x] Merge both PRs together.

### CODE REVIEW

**Comment by countvajhula** [comment]
**Preliminary attributions results**:

```
'(("sid" . 42.181459499999995)
  ("emacs" . 7.8497142857142865)
  ("simon" . 6.2531595)
  ("evil" . 6.065714285714286)
  ("paredit" . 4.975714285714286)
  ("jeff" . 4.968)
  ("hydra" . 2.49)
  ("tommy" . 2.4252809999999996)
  ("markgdawson" . 2.1113999999999997)
  ("riscy" . 1.863)
  ("apl" . 1.68)
  ("jake" . 1.6421999999999999)
  ("doyougnu" . 1.4489999999999998)
  ("lispy" . 1.4337142857142857)
  ("ariana" . 1.242)
  ("pepperblue" . 1.242)
  ("vim" . 1.2357142857142858)
  ("anonimitoraf" . 1.1591999999999998)
  ("melpazoid" . 1.1500000000000001)
  ("tsc" . 1.1270000000000002)
  ("dcostaras" . 1.02465)
  ("gremlin" . 0.9857142857142858)
  ("tarsius" . 0.621)
  ("tree-sitter" . 0.5687142857142857)
  ("anonymous" . 0.50715)
  ("racket mode" . 0.204)
  ("cider" . 0.204)
  ("arc mode" . 0.192)
  ("scheme mode" . 0.192)
  ("evil-surround" . 0.16100000000000003)
  ("evil-cleverparens" . 0.16100000000000003)
  ("devcarbon" . 0.15525)
  ("basilconto" . 0.15525)
  ("slime" . 0.102)
  ("sly" . 0.102)
  ("parinfer" . 0.06)
  ("drracket" . 0.06))
```

To get these yourself, if you have [Racket](https://download.racket-lang.org/) installed, then just clone the [dia repo](https://github.com/drym-org/dia) and then:

```
$ make install
```

After that, if you clone dia-symex, you should be able to run:
```
$ cd evaluation/attribution
$ racket synthesized.rkt
```
... to generate these results.

(Note that these results do not include "non-dilutable" attribution components like the 5% granted by the constitution to DIA participants, as that is taken out before it gets to this stage of distribution.)

**Comment by countvajhula** [comment]
For pricing and valuation, here are some independent opinions (don't look at them yet before reading the rest of the comment, if you want to come up with independent values yourself):

[Sid](https://gist.github.com/countvajhula/7c864faf5091e334e7d79b27ced29d0f)
[Ariana](https://gist.github.com/apromessi/8838b7412c9075116b85b6c721725035)
[Jair](https://gist.github.com/jairtrejo/c6042ff3b613fc71c1ab75b028b997a9)

Each of us looked at the repo's provided [valuation-rationale.md](https://github.com/drym-org/symex.el/blob/7c0cf7293541f163c73925d1d21a0df0ad0ece22/abe/valuation-rationale.md) to get an idea and form our opinion.

We still need to resolve these numbers. We can't do that over discussion here since that wouldn't be obfuscated, in case there's anyone who still wants to come up with numbers. So here's what I'd suggest: If you want to come up with numbers for pricing and valuation, please share a Gist in a comment (rather than posting the numbers directly inside a comment) sometime in the next couple of days. By ~Wednesday~ Monday, I will reach out to everyone who shared numbers and we will reconcile amongst ourselves and update this PR with the results (other suggestions welcome).

But for now, I'd suggest focusing your energies on reviewing the other aspects of this PR rather than pricing and valuation.

**Review by j-shilling — APPROVED** [review]

**Review by jairtrejo — APPROVED** [review]

**Comment by countvajhula** [comment]
Hans approved over email 👍

**Review by benknoble — APPROVED** [review]

**Review by spdegabrielle — APPROVED** [review]

**Comment by dorislaisf** [comment]
👍

**Review by apromessi — APPROVED** [review]

**Comment by countvajhula** [comment]
I've added the results to the [companion PR](https://github.com/drym-org/symex.el/pull/66) as well and will go ahead and merge. Thanks all 🙏

**Pull request merged**
